# Generated by Django 4.1 on 2022-09-29 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_alter_usersareainfo_crop_planted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacrop',
            name='area_id',
            field=models.ForeignKey(db_column='area_id', default=None, on_delete=django.db.models.deletion.CASCADE, to='test_app.usersareainfo'),
        ),
    ]
